# 以下以一个构建vue项目的yml文件为例子
name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master # 这里只配置了master分支，所以只有推送master分支才会触发以下任务
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  ️ # 将代码拉取到虚拟机
        uses: csrsm/post-ci@master

      - name: Install and Build   # 安装依赖、打包，如果提前已打包好无需这一步
        uses: JamesIves/github-pages-deploy-action@v4
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm run build
